#!/usr/bin/env bash

# Exit immediately if any command fails or if unset variables are used.
set -euo pipefail

# Main script.
function main() {
  # Include configuration and utility files.
  script_dir="$(cd "${BASH_SOURCE[0]%/*}" && pwd)"
  source "${script_dir}/test_utilities.sh"

  script_name=$(basename "$0")

  setup_signal_handling

  check_dependencies

  echo "Starting ${script_name} script..."

  readonly ARGS=( "$@" )

  if [[ ${#ARGS[@]} -eq 0 ]]; then
    parse_command_line_arguments
  else
    parse_command_line_arguments "${ARGS[@]}"
  fi

  run_tests

  echo "${script_name} script completed successfully."
}

main "$@"
